### ISSUE TITLE
Microsoft Teams CFBundleShortString mismatch

### ISSUE THREAD

**Issue by dilawarzaman** [rtrouton/autopkg_recipes#1]
Microsoft Teams uses the version 1.0.00.25152 internally in the app but 1.0.00.025152 shows up in the Info.plist as the ShortVersionString. Because of that smart group scoping not correct if you use the version criteria in the SmartGroupTemplate        

Ex:
 <criterion>
            <name>Application Version</name>
            <priority>1</priority>
            <and_or>and</and_or>
            <search_type>not like</search_type>
            <value>%VERSION%</value>
        </criterion>

**Comment by rtrouton** [comment]
I just downloaded a fresh copy and it appears that both `CFBundleShortVersionString` and `CFBundleGetInfoString` are using `1.00.025152`. Not sure what to tell you, as those two fields are the primary way I'm able to get the version information.

**Comment by dilawarzaman** [comment]
<img width="1043" alt="pastebot-dragged-image-9-21-17 1 06 36 pm-3" src="https://user-images.githubusercontent.com/6620052/30708702-cb397512-9ecd-11e7-841d-5187ddeedc53.png">
<img width="252" alt="pastebot-dragged-image-9-21-17 1 03 38 pm-2" src="https://user-images.githubusercontent.com/6620052/30708703-cb3c3888-9ecd-11e7-84f3-5c8e51f753fa.png">
<img width="785" alt="pastebot-dragged-image-9-21-17 1 05 07 pm-1" src="https://user-images.githubusercontent.com/6620052/30708701-cb37548a-9ecd-11e7-8691-9557825a280f.png">


Rich, check out these screenshots. The JSS is showing the version as CFBundleVersion (0251512). Teams shows (1.0.00.25152) and the Info.plist shows (1.0.00.025152). The issue is that Microsoft is using the build number as the CFBundleVersion instead of a full version. I'm closing this issue as it's more a Microsoft issue.
